### ISSUE TITLE
impossible to switch in VR mode since the update of the 1st february 2017 (desktop version)  

### ISSUE THREAD

**Issue by CedricBSharp** [toji/chrome-webvr-issues#136] opened 2017-02-02 15:48 UTC
Hello, 

This morning , SteamVR update itself and now i have the version of steamVR Built Jan 31, 2017 at 1:43. 
I have downloaded too the new version of chromium desktop , the version of the 1st feb 2017 (56.0.2910.0). 

Since this, I cannot launch anymore my application in VR Mode, on my HTC Vive, Steam VR remains in the mode : 
Ready 
(unresponsive) chrome.exe 

the VR mode launch some frames but after that , chromium crashes loosing the webGL context. it's a systematic issue. 
it's exactly the same behaviour when we try to launch 2 instances of VR display. 
Note that the vrrequestPresent is called as usual but it crashes some time after. 

Thanks for your help. 

![issue](https://cloud.githubusercontent.com/assets/10516436/22556402/4f2f732a-e967-11e6-8084-094ae614d7ab.png)
![steam version](https://cloud.githubusercontent.com/assets/10516436/22556404/51366eb2-e967-11e6-987f-17aeb657fb17.png)

Cédric Morel Francoz 
3DVia Development Engineer, R&D  / 3DVIA SAS
cedric.morelfrancoz@3ds.com	 	
3DS.COM/3DVIA
		

+33 1 5535 8958

**Comment by sjpt** [comment] 2017-02-02 16:23
see https://github.com/toji/chrome-webvr-issues/issues/135
This contains more details about the issue, and also a workaround.

I haven't tried relative to Jan 31 build there, only Jan 26 build, but the workaround works by reverting to an earlier build still.  However, you will also need to get the earlier ChromeVR build as well.

**Comment by ffdead** [comment] 2017-02-03 17:14
Same problem here with above versions. Only seems to crash when accessing ` navigator.getGamepads()`

**Comment by puckey** [comment] 2017-02-03 17:45
I have also been able to replicate the issue where accessing navigator.getGamepads() and then entering vr causes the browser to crash

**Comment by buesing** [comment] 2017-02-07 13:42
Have the same problem, running Chrome 56.0.2910.0, SteamVR Version from 2017-01-31

**Comment by sork** [comment] 2017-02-08 16:35
I also have the same problem with above versions. Crashes when calling navigator.getGamepads()

**Comment by jamesvecore** [comment] 2017-02-09 00:51
I'm also seeing this issue even with all versions of the webvr chromium build

**Comment by jamesvecore** [comment] 2017-02-09 00:57
Looks like the latest SteamVR beta (Feb 7th) works again!

![image](https://cloud.githubusercontent.com/assets/247507/22764438/96260e12-ee1f-11e6-9af3-1597fe9c881b.png)

**Comment by sjpt** [comment] 2017-02-09 09:55
I still don't know of a better solution than old Steam used with old Chrome VR, as in https://github.com/toji/chrome-webvr-issues/issues/135
I've seen promising report somewhere on the latest Steam beta, but haven't had a chance to try, and probably won't for the next few days.

**Comment by brianchirls** [comment] 2017-02-09 15:18
@jamesvecore Did you say this was working with the Feb 7th beta? Any idea which version of Chromium that was with? I just tried it with the Feb 1 version and Feb 7 beta, and I got the same crash.

**Comment by jamesvecore** [comment] 2017-02-09 18:23
Sorry my mistake. I thought it seemed fixed on the beta version for a bit, but it turns out I had all my gamepad code commented out from an earlier test on the non-beta build. Seems to support the case that the issue is related to the gamepad api. Once I enabled my game code on the beta steam, it started crashing again, so I deleted my comment. Sorry for the confusion.

**Comment by toji** [comment] 2017-12-27 23:01
**Closing all bugs in this issue tracker.**

This repo was created to track issues in the experimental builds WebVR Chromium builds, which are now deprecated. Chrome Canary for Windows now has much more secure (and hopefully more performant) support for WebVR [behind a flag](https://webvr.info/get-chrome/), and Android has had WebVR support as an Origin Trial and behind a flag for a while now.

If this is a performance or correctness bug and you suspect it's still happening, please test against the latest Canary build of Chrome to verify and then file a bug at https://crbug.com. If this is an issue with the API, please review the latest [WebXR explainer](https://github.com/immersive-web/webxr/blob/master/explainer.md) to see if it's been resolved and file a bug there if not.

Thanks for your interest in VR on the web! We've got an exciting year ahead of us!
*--Brandon*

**Closed by toji** 2017-12-27 23:01 UTC
