### ISSUE TITLE
Oculus CV1 (sometime) goes to black screen few seconds after presenting

### ISSUE THREAD

**Issue by tbalouet** [toji/chrome-webvr-issues#74] opened 2016-06-16 16:32 UTC
I developed a WebVR app, debugging it with the headset remaining on the head, I'm doing several "F5 then Enter VR", and one time out of 4 the display is black in the headset, even though the PC screen show the correct view and detect tracking.

Sorry, I hate those "happens once in a while" bugs but this one really does. I reproduced it with https://toji.github.io/webvr-samples/04-simple-mirroring.html (try several time to refresh then click enter vr with the headset on)

Here's a printscreen of my console if it might help
![image](https://cloud.githubusercontent.com/assets/5400381/16124599/e643e92c-33ef-11e6-980e-7fcbd2ee2912.png)

I'm using Windows 10 x64 and chromium 53.0.2744.0 (64-bit)

**Comment by toji** [comment] 2016-06-16 16:59
I had a conversation yesterday with another developer that may have explained this issue to me. I think that the problem is that the Oculus SDK in the GPU process and browser process both end up with diverging opinions on what direction "forward" is (despite my best efforts to keep them in sync.) If they're off by more than 90 deg then you'll get nothing but black because the image will be timewarped to your side or behind you every frame. At least that's my working theory for this bug.

Next time it happens try calling vrDisplay.resetPose() and see if it fixes it. If so my theory is correct and I'll see what more I can do to force them to stay in sync.

**Comment by tbalouet** [comment] 2016-06-16 17:06
Sadly just tried it out and calling resetpose from the VRControls doesn't change anything

**Comment by toji** [comment] 2016-06-16 17:22
Okay, good to know. Thanks! I'll see what else I can find.

**Comment by tbalouet** [comment] 2016-06-16 17:23
You're welcome, if I can help by taking other test please let me know

**Comment by toji** [comment] 2017-12-27 22:50
**Closing all bugs in this issue tracker.**

This repo was created to track issues in the experimental builds WebVR Chromium builds, which are now deprecated. Chrome Canary for Windows now has much more secure (and hopefully more performant) support for WebVR [behind a flag](https://webvr.info/get-chrome/), and Android has had WebVR support as an Origin Trial and behind a flag for a while now.

If this is a performance or correctness bug and you suspect it's still happening, please test against the latest Canary build of Chrome to verify and then file a bug at https://crbug.com. If this is an issue with the API, please review the latest [WebXR explainer](https://github.com/immersive-web/webxr/blob/master/explainer.md) to see if it's been resolved and file a bug there if not.

Thanks for your interest in VR on the web! We've got an exciting year ahead of us!
*--Brandon*

**Closed by toji** 2017-12-27 22:50 UTC
