### ISSUE TITLE
Déjà vu: Build will expire soon (Desktop)

### ISSUE THREAD

**Issue by Joshua-Smith** [toji/chrome-webvr-issues#156] opened 2017-08-29 14:37 UTC
It's getting close to that time again. Any ETA on a new build, and is there a summary of what will be different in this one?

**Comment by sjpt** [comment] 2017-08-29 14:41
My guess (it is no more than that, and I hope it's wrong) is that we will see another release with no changes except for the expiry date.  Luckily the early Feb (pre-expiry) release is still working pretty well, but a real almost-release-ready update would be very welcome.

**Comment by toji** [comment] 2017-08-31 18:19
I'm putting out a new build today, and unfortunately it _is_ the same build with a new expiration. (Sorry @sjpt!) But I feel like everyone is owed a bit more explanation than just "new build, go get it." given that, externally at least, Chrome's WebVR desktop progress appears to have stalled.

For the most part I've been holding out hope that I can simply stop offering the experimental builds soon in favor of having the capability behind a flag in Chrome proper. We are definitely still working on getting WebVR into Chrome's official desktop builds, aiming for Windows first. This seems like it should be a simple thing, given that it's working in the experimental builds, just land it and go, right? Unfortunately the delta between the very first "it works!" and the "it just works." is **massive**. Especially in a project as large and with as much reach as Chrome. Things that have delayed our ability to release, in no particular order are:

- License negotiations
- Security reviews
- More security reviews (Chrome is SUPER serious about security!)
- The old --use-gl=desktop flag falling into disrepair, which has forced a new render pipeline to be built around ANGLE
- Reworking the feature's internal design to avoid latency and synchronization issues found in the experimental builds.
- Driver issues
- Rebasing on the endless churn of the Chrome code base.
- Developers taking vacations (it's important!)
- Developers having families (also important!)
- Developers being redirected to more pressing issues while license and security talks are ongoing.
- Ongoing spec and development work for the next revision of WebVR.

That last one is where I've personally been spending the majority of my time. We've heard a lot of feedback from developers, users, browser vendors, and hardware manufacturers around the pain points of using the API in it's current form and what's needed to ensure the API stays useful and relevant for years to come. That feedback has been taken to heart and we're making big changes in response that will benefit everybody. The unfortunate side effect is that if I'm given a choice of spending my time on getting the long term solution finished faster or moving forward an implementation that I know will ultimately be deprecated, obviously I want to focus on getting the long term solution in place as fast as possible. That's not always very visible work to developers using the API today, though, so it creates the impression of lack of attention when in reality my life and that of several of my teammates is all WebVR, all the time these days. 😀

So apologies to all those who are using these builds to create awesome stuff! We're still working on it and still want to support you! You can get an new build with a longer expiration date (Jan 1 2018) at [the usual place](https://webvr.info/get-chrome/) today. Also, I feel no shame in suggesting that you [give Firefox a try](https://webvr.rocks/firefox#setup) for your short term desktop WebVR needs! They have an excellent and (critically) stable implementation that's enabled by default. It's not too unusual for the various browsers to have different areas of focus, and in this case Firefox chose to prioritize desktop WebVR support over mobile while Google did the opposite. That works out nicely for devs, because it means you have at least one fairly mature implementation on whatever platform you want to target. Hooray for choices on the open web! 🎉

**Comment by klausw** [comment] 2017-08-31 19:52
Personally I'd hesitate to call our Chrome on Android WebVR implementation "mature" due to known performance issues - it's nowhere near as efficient as I'd like it to be. But we do try hard to keep it standards compliant.

If you don't mind me hijacking your thread, I'd like to use this opportunity to also reassure people that getting better performance on mobile is still a top priority, but Chrome internals and GPU/driver idiosyncrasies have made this unreasonably difficult. The current WebVR render pipeline includes multiple pixel copies to get around isolation issues, including an unintended one that is finally fixed in M62. The resulting fill rate (memory bandwidth) overhead is painful, hence the low default render resolution, and performance on pixel-dense devices suffers too. On top of that the unusual render loop seems to sometimes trigger weird GPU timing which further reduces performance.

My initial attempt to speed this up via direct surface drawing ended up unusable, somehow people weren't willing to accept severe tearing in non-VR WebGL applications to make WebVR faster. Spoilsports. (I think parts of this render path are working for the Oculus browser on GearVR.)

A new prototype (with one fewer copy than the direct-to-surface drawing) looks promising, but getting it production ready is turning out to be difficult. I'm hoping to have more news to share on this in the future, but please don't hold your breath.

**Comment by shaoboyan** [comment] 2017-09-01 01:01
@klausw happy to know there is a new rendering pipeline architecture for WebVR on Android. Is there any issue or bug could trace such new architecture ? thx

**Comment by patricknelson** [comment] 2017-09-01 02:02
@toji thanks for taking the time to explain the situation. Is there any particular reason why https://webvr.info/ is no longer linking to https://webvr.info/get-chrome/ under HTC Vive? It confused me and ultimately  led me here.

Also just wanted to take this moment to share a bit of ❤️ and say **thanks** so much for the contribution from you and your team. I really appreciate the hard work everyone's put into it (both the standard and specifically in Chrome's desktop build) since this has been a huge boon for me with some of the side projects I've got going on.

**Comment by sjpt** [comment] 2017-09-01 08:20
Thank you @toji for the update; and for all the work you have been putting in behind the scenes.  The stability of the February build just before the timebomb came in has been really excellent.

**Comment by toji** [comment] 2017-09-01 16:52
@patricknelson: https://webvr.info/developers/ _does_ still link to https://webvr.info/get-chrome/. (Look for "Experimental Windows Chromium builds") but we're de-emphasizing it now because it's not seeing regular updates and we don't want to unintentionally lead users (not developers) to using it. Again, Firefox is the more stable platform at the moment for Windows WebVR and if an average user lands on webvr.info looking for "how do I try WebVR" we'd prefer that they not be using the experimental builds. (That was also the motivation for the warning and timebomb on the recent builds.)

**Comment by klausw** [comment] 2017-09-01 18:04
@shaoboyan Please see http://crbug.com/761436 which tracks the current performance work. TL;DR: new plan is to use Android O's new AHardwareBuffer instead of Surface/SurfaceTexture.

**Comment by sjpt** [comment] 2017-09-24 09:55
@toji A couple of minor details that might help users:

I found 1 Jan expiry date on the new build on this thread (and realized later it was on [release notes](https://docs.google.com/document/d/1dP9m3WLh2lsBs9jJ9LRwv1l0AtuBQAqGLAV-fUbtz2U/edit) as well), but it took a little searching.
Could you show expiry date on the page https://webvr.info/get-chrome/ itself, please?
Also fix or remove the link [Read full instructions and details here.](https://github.com/Web-VR/iswebvrready/wiki/Instructions%3A-Chromium).

If more experimental builds are needed after this one you could also show the expiry date on chrome://help/

Thanks, Stephen

**Comment by patricknelson** [comment] 2017-12-18 05:55
Part of the reason why I still use the experimental build provided by @toji is primarily because of performance reasons. For example, for some reason [this old build](https://webvr.info/get-chrome/) renders my VR stage at 70-90fps, while the new Chrome Canary renders it at only 20-30fps (if I'm lucky). I would love to start using the newer Canary builds if I could find a workaround to the performance issues. Also, the same code will update canvas in the old experimental build vs. the Canary build.

Does anyone experience both of these same issues? Personally I think it's still worth renewing this version until we can get similar performance out of Canary.

**Comment by sjpt** [comment] 2017-12-18 10:48
@patricknelson  I just did a test on three systems: 

- the very old un-timebombed chromevr, 
- the most recent timebombed one, 
- the new Canary one.  

There was not much difference between them, all gave me 90 fps on our application.    There was slightly lower cpu usage on Canary (3.8ms per frame in our app rather than 4.6ms), and slightly lower gpu usage on Canary (71% vs 75% according to Open Hardware Monitor).  The gpu results are probably not reliable as I did not replicate the exact same image.  

Fairly heavy app on i7 and 1080. [info http://mutatorvr.co.uk/](http://mutatorvr.co.uk/) [video https://vimeo.com/207269448](https://vimeo.com/207269448)

If you are on a laptop or other hybrid graphics machine, have you enabled the discrete card for Canary?
(I've forgotten more than once before)

I tried on Firefox and it was absurdly much slower; but I think that is some compatibility issue in our app.  It used to work OK generally for us, though never as well as Chrome.  Partly because we developed on Chrome so smoothed out issues as they arose; and then hit several of issues at once testing with Firefox.

I have seen cases where the image appeared on the headset but did not appear on the monitor from the same canvas; almost as if the submitFrame() call had cleared the canvas.  This is not happening on Canary.  It happened at one point when we were testing WebGL2; we do not use it regularly as there are still a couple of issues in our app if we enable it.  I seem to remember it happened on the old Firefox Nightly, but that could be a mis-memory.

**Comment by shaoboyan** [comment] 2017-12-19 01:35
@sjpt Sorry but I got the different result. I use the http://webglsamples.org/aquarium-vr/aquarium-vr.html as my test case and find that the very old experimental build indeed has better performance than latest canary(when fish number hits 1000). Would you like to share your open flags ?
p.s.  I use a computer with i7-7700k combined with GTX 1060.

**Comment by sjpt** [comment] 2017-12-19 10:26
@shaoboyan I just tested that site you mentioned and for me too it goes slower on Canary.  90 fps solid on the old build up to around 1000 fish, 60 fps or a fraction under on Canary even with just 1 fish.  Also works at 90 fps under Firefox.

The closeness to 60 fps makes it look as if something odd is happening in the requestAnimationFrame;
I can't see what it might be from a quick look.
Not sure if it is relevant, but our app which behaves well on Canary is based on three.js.

Not sure which 'open' flags you meant.
I don't think my Chrome open flags will help, but just in case (I think some of these are now dead or changed?)
```
set opts=%opts%  --disable-infobars
set opts=%opts%  --disable-session-crashed-bubble
set opts=%opts%  --enable-webvr
set opts=%opts%  --enable-features=GamepadExtensions,OpenVR
set opts=%opts%  --webvr-experimental-rendering
set opts=%opts%  --enable-unsafe-es3-apis
set opts=%opts%  --enable-webgl-draft-extensions
set opts=%opts%  -disable-application-cache
set opts=%opts%  -media-cache-size=1
set opts=%opts%  -disk-cache-size=1
set opts=%opts%  --user-data-dir="%LOCALAPPDATA%\canaryvr"
```

**Comment by shaoboyan** [comment] 2017-12-20 01:00
@sjpt thx for your info ! It seems that we have similar flags open on canary.  It's weired that you could only got 60fps in 1 fish situation. I got 85-90(not stable) fps on my device with canary. It's a pity that I cannot access your app(it's really amazing !) Do you have any other examples I could use to double check the performance ?

**Comment by klausw** [comment] 2017-12-20 01:14
@shaoboyan You could try the webvr.info slow rendering sample.

Here's the defaults which are tuned for mobile use - this is too little GPU load to stress a desktop GPU, and the workTime is too high (there's only 11ms per frame budget for 90fps):

https://webvr.info/samples/test-slow-render.html?heavyGpu=1&cubeScale=0.3&workTime=12&standardSize=true&renderScale=1.0

Try something like this for desktop, and adjust the renderScale to find a reasonable load:

https://webvr.info/samples/test-slow-render.html?heavyGpu=1&cubeScale=1.5&workTime=7&standardSize=true&renderScale=2.0

**Comment by shaoboyan** [comment] 2017-12-20 01:22
@klausw  thx !

**Comment by shaoboyan** [comment] 2017-12-20 02:12
@klausw @sjpt I tried webvr.info slow rendering sample with two settings and here's quick summary.
Although experimental has slightly better performance than canary, but canary has better quality(expermental build has critical judder issue under heavy burden).

test environment : i7-7700k + GTX1060 + HTC Vive 
settting 1 : 
https://webvr.info/samples/test-slow-render.html?heavyGpu=1&cubeScale=1.7&workTime=7&standardSize=true&renderScale=2.0
canary stable at 45fps , experimental build reach 45fps - 48fps but has slightly judder issue.
setting 2 : 
https://webvr.info/samples/test-slow-render.html?heavyGpu=1&cubeScale=1.7&workTime=7&standardSize=true&renderScale=3.0
canary reaches 19-22 fps, experimental build reach 24-25fps but has critical judder issue.

**Comment by sjpt** [comment] 2017-12-20 13:56
Slow render look a useful test.  Thanks.  
test setup: i7-6700 + GTX1080 + HTC Vive

renderScale=4.0: Canary => 39fps   old => 40fps  Firefox => 19fps
Does not render correctly to the two eyes on either Chrome, correct on Firefox.
Only using 80% gpu load on Canary

renderScale=3.0: Canary => 50fps  old => 46fps  Firefox -> 45fps

renderScale=2.0: Canary => 75fps  old => 72fps  Firefox => 86fps

Canary and Firefox are current, old is the Aug version of the experimental build.

**Comment by klausw** [comment] 2017-12-20 18:48
FYI, renderScale on this test page multiplies both width and height, so its effect is quadratic, and it's applied on top of the recommended render resolution. Setting it to 4.0 means 16x the pixels rendered, and it's possible that this exceeds limits or sanity checks in the rendering pipeline.

Assuming the default recommended render resolution of 1512x1680 per eye or 3024x1680 total, renderScale=4.0 means rendering at 12096x6720.

**Comment by sjpt** [comment] 2017-12-20 19:54
Thanks for the comment: I'll check that.  I just wanted to pump it enough enough to stress the 1080;  but it looks as if it isn't a realistic stress test done that way.

**Comment by shaoboyan** [comment] 2017-12-21 01:07
@sjpt thx for your tips about judder!

**Comment by patricknelson** [comment] 2017-12-23 05:56
Actually, I think I found something that's going to help a lot. I noticed that I had the follow major differences in FPS without any change in hardware setup whatsoever (specs below):

1. [VR Presentation](https://webvr.info/samples/03-vr-presentation.html) ([source code](https://github.com/toji/webvr.info/blob/master/samples/03-vr-presentation.html))
    - Canary: **22 FPS**
    -  Experimental: 90 FPS
1. [Simple Mirroring](https://webvr.info/samples/04-simple-mirroring.html) ([source code](https://github.com/toji/webvr.info/blob/master/samples/04-simple-mirroring.html))
    - Canary: 90 FPS
    -  Experimental: 90 FPS

Can anyone else reproduce these results? 

It looks like this is a code-related difference due to some changes between Experimental -> Canary over time. Coincidentally, my own WebVR app has **exactly** the same frame rate (22 FPS) as the first demo above in both browsers. I think it has something to do with how each frame is rendered and then sent to the VRDisplay, since I believe that's the main difference between samples 1 and 2 above. Will try to investigate further as time allows...

**Hardware:** I'm running a GTX 1080 on 3GHz i7 with no CPU load from Canary at all. Other than the fact that it's mirroring, I'm not 100% sure what the real difference is, but I'll continue to research it as time allows.

**Comment by patricknelson** [comment] 2017-12-23 06:38
Alright! So, it looks like the primary difference in performance was attributed to setting `preserveDrawingBuffer: true` when retrieving a WebGL context to draw with. I had other issues, but those appear to be not as significant and are more related to how outdated the experimental build was 😅

**Comment by sjpt** [comment] 2017-12-23 10:17
Our app uses `preserveDrawingBuffer: true` and runs at 90fps on Canary. (i7, 1080)

With `preserveDrawingBuffer: false` it runs at a very uneven mix of around 60fps and almost 90fps.
It also gives very jerky VR experience (I haven't played with SteamVR flags to see if that changes things)
and stops refreshing the image on the nonVR monitor (as might be expected).

The [chrome://flags/#webvr-experimental-rendering](url) flag in Canary may well make a difference, I seem to remember somewhere (can't remember where) that it mainly effected the last steps of transferring the image.

**Comment by klausw** [comment] 2017-12-23 23:36
`preserveDrawingBuffer` should be off for WebVR applications. Setting it to on means that it keeps the previous frame's content when starting the next frame to support incremental drawing. If you glClear at the start of each frame, there should be no visible difference between on and off. This flag won't be supported in WebXR (it never preserves the drawing buffer), and setting it to on prevents some planned optimizations, i.e. if it draws directly into a per-frame buffer it would need to do an extra copy step to fill the new buffer with the previous buffer's content.

Refreshing the image on the non-VR monitor is supposed to be independent of `preserveDrawingBuffer`, you should be able to do that in either case. The OpenVR makes a copy of the current canvas context and ships that to the VR display separately.

It's unexpected that setting the attribute to true improves performance. I suspect that there may be a bug that the canvas ends up in an inconsistent state and this reduces performance as a side effect.

The `webvr-experimental-rendering` flag has no effect on OpenVR, and at this point should also be a no-op for Android. I actually have a pending change to remove it and replace it with an Android-specific render path selector to support future optimizations. Let me know if you see it making a difference, that shouldn't be the case.

**Comment by klausw** [comment] 2017-12-23 23:43
Forgot to add - if you see a reproducible performance difference for current Canary when changing `preserveDrawingBuffer` on a public URL, or where the non-VR canvas content is not updating correctly, please file a bug at https://crbug.com/ . This GitHub tracker is just for Brandon's obsolescent experimental implementation, and we should track issues with the official builds there.

**Comment by patricknelson** [comment] 2017-12-24 02:37
> Forgot to add - if you see a reproducible performance difference for current Canary when changing preserveDrawingBuffer on a public URL

Yeah @klausw I think I might have. Have you tried comparing these two demo's in Canary? I have and I got 22fps in the first, 90fps in the second. I edited that one attribute and it was back up to 90fps. 

https://webvr.info/samples/03-vr-presentation.html
https://webvr.info/samples/04-simple-mirroring.html

See comment @ https://github.com/toji/chrome-webvr-issues/issues/156#issuecomment-353709071

**Comment by sjpt** [comment] 2017-12-24 12:00
@klausw Thank you again for your very helpful remarks.  In particular, I have noted the site for things that are clear performance bugs.  I have now disabled `preserveDrawingBuffer `and our app is going at the full rate.  

As @patricknelson says, the different SteamVR reprojection settings (for some reason 2 in the performance tab and 1 in the developer tab) can make a big difference; I must have set one of these inappropriately in my earlier experiment.  

I knew the reprojection made a huge difference to the visual experience, but had not thought it affected the frame rate out of ChromeVR.  I  had thought that the ChromeVR prepared and submitted frames at a regular rate and that the reprojection was performed further down the pipeline in OpenVR to make the best of what was submitted by ChromeVR, but it seems there may be closer interaction between the two?

If I stress our app by using higher resolutions I find that just setting 'always on' or 'asynchronous' reprojection gives the best framerates (67), and that just setting 'interleaved reprojection' gives the worst (45); setting none gives 60.  (With the old experimental I had found 'always on' easily the best.)

Does anyone have a clear diagram/explanation of what the various settings really mean?

**Comment by toji** [comment] 2017-12-27 23:06
Just echoing what Klaus said: This bug should definitely be entered into http://crbug.com at this point, given that it's observable with the Canary release. (You could link that bug back to this conversation, though. There's valuable information here.) This tracker was only meant for the experimental releases, which are now deprecated.

Thanks for helping to hunt this down!

**Closed by toji** 2017-12-27 23:06 UTC
