### ISSUE TITLE
High Latency

### ISSUE THREAD

**Issue by pyalot** [toji/chrome-webvr-issues#10] opened 2014-08-31 20:22 UTC
Around 100-120ms of latency are exhibited by the chrome build, this should be more along the lines of 30ms tops (as per oculus recommendation.

**Comment by sminnee** [comment] 2016-07-14 22:35
@toji 2 years ago this was your top priority—is this still an area that is being actively worked on?

It was great to see 90 FPS support come in, but there are definitely still some tracking issues as mentioned on #73. I don't know whether they are latency-related or something else.

It would be great to get an update on whether this is still a known issue and your best guess as to what the underlying issues are.

Thanks,
Sam

**Comment by toji** [comment] 2016-07-14 22:43
Given that this is VR latency will *ALWAYS* be a high priority, whether it's a matter of improving it or being constantly vigilant against regressions. :)

Latency today is definitely better than it was 2 years ago, and with a few exceptions I'd say it's perfectly usable. But it's still not as good as it can/should be. It's high priority, but maybe not top priority since there's plenty of other issues that affect our ability to launch the API. I'd rather have an API that everyone can use that still needs some polish than a perfectly latency free experience that nobody can use.

**Comment by sminnee** [comment] 2016-07-14 23:46
Good call. Yes, I'd agree that it's usable at the moment and I've had a lot of fun building some demos using the current Chrome builds. Keep up the good work! :-)

**Comment by DiThi** [comment] 2016-07-16 12:00
Hello @toji. Are you aware that the latency is too high for the Vive? It's at the very least a couple of frames behind, probably more. With a Rift the issue is not noticeable due to ATW, unless move your body when it's somewhat noticeable.

**Comment by toji** [comment] 2017-12-27 22:59
**Closing all bugs in this issue tracker.**

This repo was created to track issues in the experimental builds WebVR Chromium builds, which are now deprecated. Chrome Canary for Windows now has much more secure (and hopefully more performant) support for WebVR [behind a flag](https://webvr.info/get-chrome/), and Android has had WebVR support as an Origin Trial and behind a flag for a while now.

If this is a performance or correctness bug and you suspect it's still happening, please test against the latest Canary build of Chrome to verify and then file a bug at https://crbug.com. If this is an issue with the API, please review the latest [WebXR explainer](https://github.com/immersive-web/webxr/blob/master/explainer.md) to see if it's been resolved and file a bug there if not.

Thanks for your interest in VR on the web! We've got an exciting year ahead of us!
*--Brandon*

**Closed by toji** 2017-12-27 22:59 UTC
