### ISSUE TITLE
Oculus Rift CV1: stuck at "Please Wait"

### ISSUE THREAD

**Issue by darknoon** [toji/chrome-webvr-issues#146] opened 2017-04-25 03:42 UTC
I was having this issue with Firefox as well, but that was resolved after I updated to the beta channel on my oculus software.

Now Firefox nightly is working but not the special chromium build posted on webvr.rocks.

I'm testing with https://webvr.info/samples/03-vr-presentation.html, clicked enter vr no dice. Just stuck at the loading spinner and eventually says "chrome.exe is taking a while to load. if this issue persists..." etc.

**Comment by darknoon** [comment] 2017-04-25 03:44
Also, it's worth noting that orientation does seem to be going through since the scene will rotate on my main display though nothing is showing up in the HMD.

**Comment by huningxin** [comment] 2017-05-05 05:15
It seems the same root cause of https://github.com/toji/chrome-webvr-issues/issues/147.

**Comment by stevel4857** [comment] 2017-06-22 22:01
I updated months ago and I only hear sound and still see nothing in the headset except please wait. Oculus CV1 win10 with NVidea1080ti.

**Comment by adammarcwilliams** [comment] 2017-07-05 13:29
Oddly enough I had Chrome working & FireFox pausing on please wait about a month back but now after updating to latest browser builds and up-to date Oculus Home I cant use Chrome but FireFox works fine.

I am getting the "Please Wait - Taking Longer Than Usual" screen. 

Oculus CV1, Oculus Home 1.16.0.409144. GTX 1060

**Comment by hamishtodd1** [comment] 2017-12-11 12:47
I had this issue but it went away when I updated my video drivers to 388.59.

(Here was me thinking that the goddamn point of multiple pieces of nvidia crapware on my computer was that such updates happened automatically, but no, I still have to go to the website which tries to detect what I already have USING JAVA ARRRGH and then fails and I take a guess that I'll just update to the most recent ones and then it crashes while installing 3D vision which nobody needs why the hell is this so in need of updating so I have to hard reset my computer twice and then do a "custom install" to avoid 3D vision I hate computers)

**Comment by toji** [comment] 2017-12-27 22:43
**Closing all bugs in this issue tracker.**

This repo was created to track issues in the experimental builds WebVR Chromium builds, which are now deprecated. Chrome Canary for Windows now has much more secure (and hopefully more performant) support for WebVR [behind a flag](https://webvr.info/get-chrome/), and Android has had WebVR support as an Origin Trial and behind a flag for a while now.

If this is a performance or correctness bug and you suspect it's still happening, please test against the latest Canary build of Chrome to verify and then file a bug at https://crbug.com. If this is an issue with the API, please review the latest [WebXR explainer](https://github.com/immersive-web/webxr/blob/master/explainer.md) to see if it's been resolved and file a bug there if not.

Thanks for your interest in VR on the web! We've got an exciting year ahead of us!
*--Brandon*

**Closed by toji** 2017-12-27 22:43 UTC
