### ISSUE TITLE
WebVR Boilerplate only rendering chaperone bounds (and not clearing them)

### ISSUE THREAD

**Issue by stuartpb** [toji/chrome-webvr-issues#64] opened 2016-05-16 22:16 UTC
- Chrome WebVR build Version 52.0.2715.0 
- SteamVR (beta) 1463169981

Clicking the VR Mode button only shows the Chaperone bounds of my play space, which remain drawn (ie. waves of persistent lines).

**Comment by stuartpb** [comment] 2016-05-18 10:59
Looping in Twitter: https://twitter.com/stuartpb/status/732328425898135552

**Comment by stuartpb** [comment] 2016-05-18 11:11
This is on an AMD R9 390 with Catalyst 16.3.2. I'm going to reluctantly try Catalyst 16.5.2.1 to see if it fixes this, although I'm not getting my hopes up.

**Comment by stuartpb** [comment] 2016-05-22 01:53
Driver update did not fix. Still happens with this morning's Chromium WebVR build.

**Comment by stuartpb** [comment] 2016-05-22 08:16
Switching the headset out of Direct Mode doesn't affect this issue.

**Comment by robertlong** [comment] 2016-05-28 21:31
I'm seeing the same thing. Also on a Radeon 390.

**Comment by stuartpb** [comment] 2016-05-31 17:16
Here's some log output that I thought I posted to Twitter a week ago that doesn't seem to have gone through:

## from debug.log, looks a few days old

```
[0521/185216:ERROR:process_info.cc(608)] range at 0xe2ae1cb600000000, size 0x21a fully unreadable
[0521/185216:ERROR:process_info.cc(608)] range at 0xe2ae1cd600000000, size 0x21a fully unreadable
[0521/185216:ERROR:process_info.cc(608)] range at 0x0, size 0x21a fully unreadable
[0521/185216:WARNING:in_range_cast.h(38)] value 2314640317246 out of range
[0521/185216:WARNING:in_range_cast.h(38)] value 2314640315210 out of range
[0521/185216:WARNING:in_range_cast.h(38)] value 2314640317286 out of range
[0521/185216:WARNING:in_range_cast.h(38)] value 2314495971488 out of range
[0521/185216:WARNING:in_range_cast.h(38)] value 108084205055182070 out of range
[0521/185216:WARNING:in_range_cast.h(38)] value 2314496085008 out of range
```

## in console, just now

```
[2016:16040:0524/204820:ERROR:gles2_cmd_decoder.cc(2309)] [.Offscreen-MainThread-000002142E288E00]GL ERROR :GL_INVALID_OPERATION : BackFramebuffer::Destroy: <- error from previous GL command
[2016:16040:0524/204827:ERROR:gles2_cmd_decoder.cc(8305)] [.Offscreen-For-WebGL-000001C2276177E0]RENDER WARNING: texture bound to texture unit 0 is not renderable. It maybe non-power-of-2 and have incompatible texture filtering.
```

(previous line repeats a bunch of times)

``` 
[2016:16040:0524/205013:ERROR:gles2_cmd_decoder.cc(2309)] [.Offscreen-MainThread-000001C2274094A0]GL ERROR :GL_INVALID_OPERATION : BackFramebuffer::Destroy: <- error from previous GL command
```

**Comment by stuartpb** [comment] 2016-05-31 17:19
@toji LMK if you want more info, maybe with stuff from https://www.chromium.org/developers/how-tos/debugging-gpu-related-code

**Comment by brianpeiris** [comment] 2016-06-08 07:37
Same issue here on my R9 380, driver 16.15.2211. I can reproduce the problem with the basic "VR Presentation" sample.

**Comment by stuartpb** [comment] 2016-06-16 19:42
@toji Any progress on this?

**Comment by robertlong** [comment] 2016-06-16 22:47
@stuartpb do these examples work for you in the latest experimental Chromium?
https://playcanv.as/p/iUgfldxp/
https://toji.github.io/webvr-samples/03-vr-presentation.html

It just started working for me yesterday. The Three.js Vive example is still broken.

**Comment by stuartpb** [comment] 2016-06-17 01:24
Nope, just tried the latter in Version 53.0.2744.0 (64-bit), issue still present.

**Comment by brianpeiris** [comment] 2016-06-21 05:19
Oh, woah. The playcanvas example works for me but the vr-presentation one doesn't (it exhibits the issue). I'm using version 52 (it looks like version 53 is no longer available for download).

**Comment by brianpeiris** [comment] 2016-06-21 05:23
This simpler playcanvas demo works for me as well https://playcanvas.github.io/webvr/examples/simple-scene/

**Comment by lollerbus** [comment] 2016-06-29 20:20
Can confirm that https://playcanvas.github.io/webvr/examples/simple-scene/ works, but https://toji.github.io/webvr-samples/03-vr-presentation.html does not on Version 53.0.2783.0 (https://drive.google.com/file/d/0BzudLt22BqGRR1NFWHlLR1MyZ2c/view). 

Catalyst 16.6.1, HD 7970

**Comment by stuartpb** [comment] 2016-06-29 22:19
I'm encountering the same behavior with the new build of Chromium that was just posted today (in SteamVR, there's a red "(unresponsive)" when visiting the latter demo): could this maybe have something to do with the way that the former mirrors its view to the primary display, but the latter does not?

**Comment by SBUtltmedia** [comment] 2016-07-08 22:29
We are also having the same issue, https://playcanvas.github.io/webvr/examples/simple-scene/ is the only demo that I've seen work in the browser so far. Running in windows 10 with Dual AMD FirePro D700

**Comment by dddExperiments** [comment] 2016-08-05 07:09
Same here. I have R9 390X with Cathalist 16.7.3 on Windows 10.

https://playcanv.as/p/iUgfldxp/ - is working fine
https://toji.github.io/webvr-samples/03-vr-presentation.html - vr headset orientation is properly updated but it's only displaying the chaperon without clearing it, see screenshot bellow:

![chaperon_bug](https://cloud.githubusercontent.com/assets/439960/17428715/662b495c-5a9f-11e6-833d-fcf9ada6890e.png)

I'm running chrome with  --ignore-gpu-blacklist and I've this log from about:gpu:
![about_gpu](https://cloud.githubusercontent.com/assets/439960/17428900/757e79a0-5aa0-11e6-9743-7b93f604ecd4.png)

Webvr seems very promissing and I would like to play with it :)
Please let me know if you want more details.
Thanks!

**Comment by brianpeiris** [comment] 2016-08-21 18:30
The new version of a-frame works, so it must be something particular about the samples https://aframe.io/aframe/examples/showcase/tracked-controls/

**Comment by spite** [comment] 2016-09-05 23:36
This usually happens if you resize the canvas that you're presenting. In three.js case specifically, it happens if your call renderer.setSize after effect.setSize, for instance. Hope it helps.

**Comment by Avnerus** [comment] 2016-10-05 23:13
I had a similar problem and it was fixed setting `{alpha: true}` when constructing *WebGLRenderer*

**Comment by dddExperiments** [comment] 2016-10-06 04:12
Thanks a lot @Avnerus!
I've locally patched the demos with your suggested fix and it's working perfectly at 90 fps 😄.

**Comment by toji** [comment] 2017-12-27 22:58
**Closing all bugs in this issue tracker.**

This repo was created to track issues in the experimental builds WebVR Chromium builds, which are now deprecated. Chrome Canary for Windows now has much more secure (and hopefully more performant) support for WebVR [behind a flag](https://webvr.info/get-chrome/), and Android has had WebVR support as an Origin Trial and behind a flag for a while now.

If this is a performance or correctness bug and you suspect it's still happening, please test against the latest Canary build of Chrome to verify and then file a bug at https://crbug.com. If this is an issue with the API, please review the latest [WebXR explainer](https://github.com/immersive-web/webxr/blob/master/explainer.md) to see if it's been resolved and file a bug there if not.

Thanks for your interest in VR on the web! We've got an exciting year ahead of us!
*--Brandon*

**Closed by toji** 2017-12-27 22:58 UTC
