### ISSUE TITLE
"Your browser does not support WebVR"

### ISSUE THREAD

**Issue by MrTrustworthy** [toji/chrome-webvr-issues#65] opened 2016-05-19 18:40 UTC
Windows 10, Oculus Rift v. 1.3.2, Chromium build from https://webvr.info/get-chrome/, WebVR flag set.

Navigating to the examples in aframe.io, I get the message (after hovering on the VR button on the bottom right)
"Your browser does not support WebVR. To enter VR, use a VR-compatible browser or a mobile phone.Learn more."

Other WebVR sites also do not work. Since that Chromium build is from april 24, I can only assume that some new Oculus runtime versions broke it.

Is this project still maintained?

**Comment by mroosen** [comment] 2016-05-22 20:56
I'm experiencing the same issue, downloaded chromium_webvr_v1_win64.7z from 21 of May. WebVR flag set in chrome://flags... Nothing works on mozvr.com! 

Can I give some more information perhaps to find out what I'm missing ?

**Comment by capnmidnight** [comment] 2016-05-22 21:06
So the issue is actually that mozvr.com doesn't support WebVR 1.0. They
track Firefox Nightly, and AFAIK Nightly has implemented support for the v1
draft proposal yet. The word I've heard is that it should be "any day now".

**Comment by toji** [comment] 2017-12-27 22:58
**Closing all bugs in this issue tracker.**

This repo was created to track issues in the experimental builds WebVR Chromium builds, which are now deprecated. Chrome Canary for Windows now has much more secure (and hopefully more performant) support for WebVR [behind a flag](https://webvr.info/get-chrome/), and Android has had WebVR support as an Origin Trial and behind a flag for a while now.

If this is a performance or correctness bug and you suspect it's still happening, please test against the latest Canary build of Chrome to verify and then file a bug at https://crbug.com. If this is an issue with the API, please review the latest [WebXR explainer](https://github.com/immersive-web/webxr/blob/master/explainer.md) to see if it's been resolved and file a bug there if not.

Thanks for your interest in VR on the web! We've got an exciting year ahead of us!
*--Brandon*

**Closed by toji** 2017-12-27 22:58 UTC
